# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy

  cache:
    paths:
      - node_modules/

  image: node:lts-alpine

  script:
    - npm i -D
    - npm run build-docs
    
  artifacts:
    paths:
      - public
  only:
    - master